"""Portal index generator and highlight extraction for Specola."""
from __future__ import annotations

import re
from datetime import date
from pathlib import Path

# ---------------------------------------------------------------------------
# Regex helpers
# ---------------------------------------------------------------------------
_BOLD_RE = re.compile(r"\*\*(.+?)\*\*")
_LINK_RE = re.compile(r"\[([^\]]+)\]\([^)]+\)")
_NUMBERED_RE = re.compile(r"^\d+\.\s+")
_HTML_TAG_RE = re.compile(r"<[^>]+>")
_DATE_IN_FILENAME_RE = re.compile(r"Specola_(\d{4}-\d{2}-\d{2})")

# ---------------------------------------------------------------------------
# Sections that contain the highlights (IT and EN)
# ---------------------------------------------------------------------------
_HIGHLIGHT_HEADINGS = {"## Da sapere oggi", "## Key takeaways"}

# ---------------------------------------------------------------------------
# Index template
# ---------------------------------------------------------------------------
_INDEX_TEMPLATE = """\
<!DOCTYPE html>
<html lang="{lang}">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Specola — {archive_label}</title>
<style>
  *, *::before, *::after {{ box-sizing: border-box; margin: 0; padding: 0; }}

  body {{
    font-family: Georgia, 'Times New Roman', serif;
    font-size: 11pt;
    line-height: 1.6;
    color: #374151;
    background: #f9fafb;
    max-width: 680px;
    margin: 0 auto;
    padding: 2.5cm 1.5cm;
  }}

  .portal-header {{
    display: flex;
    justify-content: space-between;
    align-items: baseline;
    font-size: 8pt;
    color: #6b7280;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    border-bottom: 1px solid #d1d5db;
    padding-bottom: 0.4em;
    margin-bottom: 1.5em;
  }}

  .portal-header .brand {{
    font-weight: bold;
    color: #e94560;
    font-size: 10pt;
    text-transform: none;
    letter-spacing: 0;
  }}

  h1 {{
    font-size: 22pt;
    font-weight: bold;
    color: #1a1a2e;
    margin-bottom: 0.2em;
    padding-bottom: 0.25em;
    border-bottom: 3px solid #e94560;
  }}

  .meta {{
    font-size: 9pt;
    color: #6b7280;
    margin-bottom: 2em;
  }}

  .card {{
    background: #ffffff;
    border: 1px solid #e5e7eb;
    border-radius: 6px;
    padding: 1.2em 1.4em;
    margin-bottom: 1em;
    text-decoration: none;
    display: block;
    color: inherit;
    transition: box-shadow 0.15s;
  }}

  .card:hover {{
    box-shadow: 0 2px 8px rgba(0,0,0,0.08);
  }}

  .card.today {{
    border-left: 4px solid #e94560;
  }}

  .card-header {{
    display: flex;
    justify-content: space-between;
    align-items: baseline;
    margin-bottom: 0.5em;
  }}

  .card-date {{
    font-size: 10pt;
    font-weight: bold;
    color: #1a1a2e;
  }}

  .card-label {{
    font-size: 8pt;
    font-weight: bold;
    color: #e94560;
    text-transform: uppercase;
    letter-spacing: 0.05em;
  }}

  .card ul {{
    margin: 0.4em 0 0 1.2em;
    padding: 0;
  }}

  .card li {{
    font-size: 9.5pt;
    color: #4b5563;
    margin-bottom: 0.2em;
  }}

  .portal-footer {{
    font-size: 8pt;
    color: #6b7280;
    text-align: center;
    border-top: 1px solid #d1d5db;
    padding-top: 0.4em;
    margin-top: 2em;
  }}
</style>
</head>
<body>

<div class="portal-header">
  <span class="brand">Specola</span>
  <span>{today_display}</span>
</div>

<h1>{archive_label}</h1>
<p class="meta">{count} {number_label}</p>

{cards}

<div class="portal-footer">{footer_label} &mdash; {today_display}</div>
</body>
</html>"""

# ---------------------------------------------------------------------------
# Labels
# ---------------------------------------------------------------------------
_LABELS = {
    "it": {
        "archive": "Archivio",
        "number": lambda n: "Specola" if n == 1 else "Specole",
        "today": "Oggi",
        "footer": "Generato da Specola",
    },
    "en": {
        "archive": "Archive",
        "number": lambda n: "briefing" if n == 1 else "briefings",
        "today": "Today",
        "footer": "Generated by Specola",
    },
}


# ---------------------------------------------------------------------------
# Private helpers
# ---------------------------------------------------------------------------

def _strip_inline_markdown(text: str) -> str:
    """Remove bold markers and links, keeping plain text."""
    text = _LINK_RE.sub(r"\1", text)
    text = _BOLD_RE.sub(r"\1", text)
    return text.strip()


def _date_from_filename(name: str) -> str | None:
    """Extract ISO date string from a filename like 'Specola_2026-04-05.html'."""
    m = _DATE_IN_FILENAME_RE.search(name)
    return m.group(1) if m else None


def _extract_preview_from_html(html_path: Path, max_items: int = 3) -> list[str]:
    """Return up to max_items plain-text list items from the HTML file."""
    try:
        content = html_path.read_text(encoding="utf-8")
    except OSError:
        return []

    items = re.findall(r"<li>(.*?)</li>", content, re.DOTALL)
    result = []
    for raw in items[:max_items]:
        plain = _HTML_TAG_RE.sub("", raw)
        plain = plain.strip()
        if plain:
            result.append(plain)
    return result


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def extract_highlights(markdown: str) -> list[str]:
    """Extract up to 5 plain-text highlights from 'Da sapere oggi' / 'Key takeaways'.

    Returns an empty list if the section is not found.
    """
    lines = markdown.split("\n")
    in_section = False
    results: list[str] = []

    for line in lines:
        stripped = line.strip()

        if stripped in _HIGHLIGHT_HEADINGS:
            in_section = True
            continue

        if in_section:
            # Stop at the next H2/H1 heading
            if stripped.startswith("## ") or stripped.startswith("# "):
                break

            # Bullet: dash or star
            if stripped.startswith("- ") or stripped.startswith("* "):
                text = _strip_inline_markdown(stripped[2:])
                if text:
                    results.append(text)

            # Numbered item
            elif _NUMBERED_RE.match(stripped):
                text = _strip_inline_markdown(_NUMBERED_RE.sub("", stripped))
                if text:
                    results.append(text)

            if len(results) >= 5:
                break

    return results


def regenerate_portal_index(output_dir: str | Path, language: str = "it") -> str:
    """Scan output_dir for Specola_*.html files and regenerate index.html.

    Returns the path to the generated index.html.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    labels = _LABELS.get(language, _LABELS["it"])
    today_str = date.today().isoformat()

    # Collect briefing files (exclude index.html itself)
    entries: list[tuple[str, Path]] = []
    for html_file in output_dir.glob("Specola_*.html"):
        if html_file.name == "index.html":
            continue
        date_str = _date_from_filename(html_file.name)
        if date_str:
            entries.append((date_str, html_file))

    # Sort newest first
    entries.sort(key=lambda x: x[0], reverse=True)

    # Build cards
    card_parts: list[str] = []
    for date_str, html_file in entries:
        is_today = date_str == today_str
        card_class = 'class="card today"' if is_today else 'class="card"'
        label_html = (
            f'<span class="card-label">{labels["today"]}</span>' if is_today else ""
        )

        preview_items = _extract_preview_from_html(html_file, max_items=3)
        if preview_items:
            li_items = "\n".join(f"      <li>{item}</li>" for item in preview_items)
            preview_html = f"    <ul>\n{li_items}\n    </ul>"
        else:
            preview_html = ""

        card_parts.append(
            f'<a href="{html_file.name}" {card_class}>\n'
            f'  <div class="card-header">\n'
            f'    <span class="card-date">{date_str}</span>\n'
            f"    {label_html}\n"
            f"  </div>\n"
            f"{preview_html}\n"
            f"</a>"
        )

    cards_html = "\n".join(card_parts)
    count = len(entries)
    number_label = labels["number"](count)

    html = _INDEX_TEMPLATE.format(
        lang=language,
        archive_label=labels["archive"],
        count=count,
        number_label=number_label,
        cards=cards_html,
        footer_label=labels["footer"],
        today_display=today_str,
    )

    index_path = output_dir / "index.html"
    index_path.write_text(html, encoding="utf-8")
    return str(index_path)
